FROM balenalib/raspberrypi3-node

WORKDIR /usr/src/app

COPY public/ public/
COPY index.html index.html
COPY package.json package.json
COPY package-lock.json package-lock.json
COPY server.js server.js
COPY scripts/ scripts/

RUN npm install
# RUN ln -s /data /usr/src/app/public/data

CMD ./scripts/start.sh
